### PR TITLE
Spelling error of the century

### PR DESCRIPTION
**Pull request by alucard0134**

### CODE REVIEW

**Comment by nokonoko** [comment]
IIRC this is in place to actually correct a spelling error in a previous version of Pomf.

**Comment by alucard0134** [comment]
Hm, so remind me why the schema.sql column name is originalname but then fails miserably when trying to update the column. Shouldn't the column in schema.sql be changed to orginalname in this case?

**Comment by nokonoko** [comment]
oh right derp

**Comment by rinukkusu** [comment]
thx :|

**Comment by alucard0134** [comment]
So now you notice :|. Any who it's resolved now.

**Pull request merged**
