### PR TITLE
First changes

### PR DESCRIPTION
**Pull request by pinetreegator**
Removed weeaboo shit images and added Mr. Sugoi, donate note is now a
warning beta note, changed the title and the favicon, and added a
#/jp/shows link and Sugoi’s fork link at the bottom for support
purposes.

### CODE REVIEW

**Comment by avail** [comment]
thefuck kind of drugs are you on

**Comment by on-three** [comment]
sugoi

**Comment by pinetreegator** [comment]
I'm sorry I'm new to github, I don't really know how to use it. just ignore me

also i didn't write that someone else did

**Comment by TheHowl** [comment]
what the fuck

**Comment by Madotsukii** [comment]
I had a hearty kek.

**Comment by iiiGerardoiii** [comment]
oh shit pinetreegator what are you doing

**Comment by nokonoko** [comment]
This was supposed to be a pull for a fork I assume?

**Comment by pinetreegator** [comment]
yes.

**Pull request closed without merging**
